<?php
/**
 * Copyright © 2019 MagestyApps. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \MagestyApps\FBComments\Block\Config $block */
?>

<?php if ($appId = $block->getAppId()): ?>
<meta property="fb:app_id" content="<?php echo $appId; ?>" />
<?php elseif ($admins = $block->getAdmins()): ?>

<?php foreach ($admins as $adminId): ?>
<meta property="fb:admins" content="<?php echo trim($adminId); ?>" />
<?php endforeach; ?>

<?php endif; ?>

